### ISSUE TITLE
Dripcap not starting on windows 10 x64

### ISSUE THREAD

**Issue by michaelpittino** [dripcap/dripcap#15]
Hello, dripcap 0.5.1 does not start for me. I use windows 10 x64. The Dripcap processes are created but no window shows up.

**Comment by h2so5** [comment]
This issue is related to Riot,js bug: https://github.com/riot/riot/pull/2131

**Comment by michaelpittino** [comment]
According to the issue there it is already fixed. Any chance of releasing a new version of dripcap with the bugfix included? Many thanks.

**Comment by h2so5** [comment]
That could take a while because I'm working on another issue about upgrading riot v3.0.2 to v3.0.5.

**Comment by michaelpittino** [comment]
I see, would you mind updating this issue as you fix it?

**Comment by h2so5** [comment]
The issue about upgrading riot.js seems to be troublesome.
So I have just released v0.5.2 with a workaround for this issue.
Thank you for your reporting!
