### ISSUE TITLE
Build from source Mac instructions

### ISSUE THREAD

**Issue by makenova** [dripcap/dripcap#16]
Hi,

## issue

When trying to install from source by following the Mac instructions in the [Git Book](https://docs.dripcap.org/build/mac.html) I get the following error during the default gulp task.

```sh
[11:39:08] Starting 'default'...
[11:39:08] 'default' errored after 8.16 ms
[11:39:08] Error: Command failed: electron --enable-logging .build
/bin/sh: electron: command not found
```

## solution

I was able to resolve the issue by either: 
 * modifying the default gulp task to use the local electron version
 *  by installing electron globally

### modify default gulp task

Change the default gulp task from this:

```js
gulp.task('default', ['build'], cb => {
  let env = {
    DRIPCAP_ATTACH: '1'
  };
  exec('electron --enable-logging .build', {
    env: Object.assign(env, process.env)
  }, cb);
});
```

 to this:

```js
gulp.task('default', ['build'], cb => {
  let env = {
    DRIPCAP_ATTACH: '1'
  };
  let electronPath = `${__dirname}/node_modules/.bin`
  exec(`${electronPath}/electron --enable-logging .build`, {
    env: Object.assign(env, process.env)
  }, cb);
});
```

### install electron globally

```sh
npm install -g electron
# OR
yarn global add electron
```

I prefer not to use global dependencies, so modifying the default gulp task is my preferred solution. 
Thanks for the great application and your time.

**Comment by h2so5** [comment]
@makenova Thank you 😸 !
