### ISSUE TITLE
Windows download?

### ISSUE THREAD

**Issue by michaelpittino** [dripcap/dripcap#2]
Hello, I took a look at the wiki which says: `Visit Releases and download dripcap-windows-amd64.zip.`
Sadly I can't find a windows package in the releases list.

**Comment by amilajack** [comment]
Can you build it yourself?

**Comment by michaelpittino** [comment]
I have no experience with electron - could you give me a short instruction how to do so?

**Comment by amilajack** [comment]
Now that I look into it, there actually aren't any instructions on how to build from source. @h2so5 what are the steps to do so?

**Comment by h2so5** [comment]
@michaelpittino 
Sorry, the windows binary had a trouble and it has been removed currently.
I'm going to fix it and deploy a new windows binary soon.

**Comment by michaelpittino** [comment]
Would you still add steps to compile the source for windows? Thank you very much.

**Comment by h2so5** [comment]
@michaelpittino 
I wrote build instructions for v0.4.x . Thank you for waiting!
https://github.com/dripcap/dripcap/wiki/Build-from-source#windows
