### ISSUE TITLE
Feature request: Make up/down arrow keys move between packets in list

### ISSUE THREAD

**Issue by unfo** [dripcap/dripcap#5]
**Problem statement**
Currently selecting a packet in the left window and pressing up/down arrow keys does not select the previous/next packet.

It would be very useful and intuitive for it to do so.

**System information**
- OSX 10.11.6
- Dripcap 0.3.9

**Comment by h2so5** [comment]
Closed via https://github.com/dripcap/dripcap/commit/12cb94f9632ad5953a1aab9deb94fe17a53a0763
