### ISSUE TITLE
No interface names in OSX

### ISSUE THREAD

**Issue by dzoba** [dripcap/dripcap#6]
Nothing happens when I click the box, nor can I type anything into it.  Also, a minor thing, theres no label on the box so I didn't really know what it was at first.

![image](https://cloud.githubusercontent.com/assets/857664/18855141/513c306c-8405-11e6-826c-7aaecaabb322.png)

**Comment by bassu** [comment]
Same issue. Cannot start capturing as well. I'm not sure what's impeding since log is empty!

**Comment by riyaz** [comment]
Same here, its in macOs sierra if that helps.

**Comment by stirch** [comment]
I had the same issue. Later I tried to launch app Dripcap from Alfred app, after that I had prompted for rights to install Helper Tool and it's work now.

**Comment by jeroenherczeg** [comment]
Same here, sierra

**Comment by h2so5** [comment]
Helper App for macOS has been updated.
Please try v0.4.0.

**Comment by KalenAnson** [comment]
I am still seeing this issue, just downloaded version 0.4.9 and I am running OSX 10.10.3.

**Comment by h2so5** [comment]
@KalenAnson  
This issue may depend on OSX version. Unfortunately, I have no machine running OSX Yosemite.
By the way, in Debian Linux, you need the newer version of libstdc++ (>= GLIBCXX_3.4.21, Related to https://github.com/dripcap/dripcap/issues/8 ).

**Comment by h2so5** [comment]
I fixed some related bugs and this problem would be solved.
However I didn't test it on the older macOS.
