### ISSUE TITLE
Problem with dripcap Linux Mint Rosa 

### ISSUE THREAD

**Issue by merlinnusr** [dripcap/dripcap#8]
/usr/bin/goldfilter: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/bin/goldfilter)
/usr/bin/goldfilter: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/bin/goldfilter)
/usr/bin/goldfilter: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/bin/goldfilter)

What dependencies need dripcap ?

**Comment by h2so5** [comment]
Dripcap depends on the newer version of glibc.
Please try following:

```
$ sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
$ sudo apt-get update
$ sudo apt-get install libstdc++6
```
From http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
